# dataset
root_path: "/opt/vineet-workspace/datasets/kitti_tracking/training"

input_size: 4
# val_seqs: [4, 11, 17, 20]
val_seqs: [4]
train_seqs: [0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 18, 19]
# train_seqs: [0]

test_seqs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]

# tracking type
tracking_type: ["Car", "Van"]

# training
pin_memory: True


